export const jogadores = [
  {
    agilidade: 86,
    altura: 170,
    clube_atual: "Inter Miami",
    codigo_jogador: 1001,
    drible: 95,
    forca: 68,
    foto: "imagem1.jpg",
    idade: 38,
    nacionalidade: "Argentina",
    nome: "Lionel Messi",
    peso: 72,
    posicao: "PD",
    velocidade: 82
  },
  {
    agilidade: 91,
    altura: 175,
    clube_atual: "Al Nassr",
    codigo_jogador: 1002,
    drible: 88,
    forca: 79,
    foto: "imagem2.png",
    idade: 41,
    nacionalidade: "Portugal",
    nome: "Cristiano Ronaldo",
    peso: 83,
    posicao: "ATA",
    velocidade: 84
  },
  {
    agilidade: 94,
    altura: 175,
    clube_atual: "Santos",
    codigo_jogador: 1003,
    drible: 93,
    forca: 61,
    foto: "imagem3.jpg",
    idade: 34,
    nacionalidade: "Brasil",
    nome: "Neymar Jr",
    peso: 68,
    posicao: "PE",
    velocidade: 87
  },
  {
    agilidade: 88,
    altura: 180,
    clube_atual: "Real Madrid",
    codigo_jogador: 1004,
    drible: 91,
    forca: 75,
    foto: "imagem4.png",
    idade: 26,
    nacionalidade: "França",
    nome: "Kylian Mbappe",
    peso: 73,
    posicao: "ATA",
    velocidade: 98
  },
  {
    agilidade: 90,
    altura: 181,
    clube_atual: "Manchester City",
    codigo_jogador: 1005,
    drible: 90,
    forca: 74,
    foto: "imagem5.jpg",
    idade: 25,
    nacionalidade: "Noruega",
    nome: "Erling Haaland",
    peso: 88,
    posicao: "ATA",
    velocidade: 89
  },
  {
    agilidade: 89,
    altura: 172,
    clube_atual: "Liverpool",
    codigo_jogador: 1006,
    drible: 89,
    forca: 71,
    foto: "imagem6.png",
    idade: 33,
    nacionalidade: "Egito",
    nome: "Mohamed Salah",
    peso: 71,
    posicao: "PD",
    velocidade: 90
  },
  {
    agilidade: 84,
    altura: 188,
    clube_atual: "Bayern de Munique",
    codigo_jogador: 1007,
    drible: 85,
    forca: 82,
    foto: "imagem7.jpg",
    idade: 31,
    nacionalidade: "Inglaterra",
    nome: "Harry Kane",
    peso: 86,
    posicao: "ATA",
    velocidade: 78
  },
  {
    agilidade: 92,
    altura: 176,
    clube_atual: "Real Madrid",
    codigo_jogador: 1008,
    drible: 92,
    forca: 69,
    foto: "imagem8.png",
    idade: 25,
    nacionalidade: "Brasil",
    nome: "Vinicius Junior",
    peso: 73,
    posicao: "PE",
    velocidade: 96
  },
  {
    agilidade: 86,
    altura: 177,
    clube_atual: "Barcelona",
    codigo_jogador: 1009,
    drible: 88,
    forca: 65,
    foto: "imagem9.jpg",
    idade: 18,
    nacionalidade: "Espanha",
    nome: "Lamine Yamal",
    peso: 72,
    posicao: "PD",
    velocidade: 87
  },
  {
    agilidade: 87,
    altura: 182,
    clube_atual: "Manchester City",
    codigo_jogador: 1010,
    drible: 91,
    forca: 73,
    foto: "imagem10.png",
    idade: 34,
    nacionalidade: "Bélgica",
    nome: "Kevin De Bruyne",
    peso: 76,
    posicao: "MC",
    velocidade: 76
  },
  {
    agilidade: 88,
    altura: 184,
    clube_atual: "Arsenal",
    codigo_jogador: 1011,
    drible: 87,
    forca: 74,
    foto: "imagem11.jpg",
    idade: 27,
    nacionalidade: "Noruega",
    nome: "Martin Odegaard",
    peso: 68,
    posicao: "MEI",
    velocidade: 75
  },
  {
    agilidade: 80,
    altura: 193,
    clube_atual: "Manchester City",
    codigo_jogador: 1012,
    drible: 76,
    forca: 92,
    foto: "imagem12.png",
    idade: 28,
    nacionalidade: "Portugal",
    nome: "Ruben Dias",
    peso: 82,
    posicao: "ZAG",
    velocidade: 72
  },
  {
    agilidade: 85,
    altura: 183,
    clube_atual: "Liverpool",
    codigo_jogador: 1013,
    drible: 84,
    forca: 81,
    foto: "imagem13.jpg",
    idade: 33,
    nacionalidade: "Holanda",
    nome: "Virgil van Dijk",
    peso: 92,
    posicao: "ZAG",
    velocidade: 79
  },
  {
    agilidade: 93,
    altura: 174,
    clube_atual: "Barcelona",
    codigo_jogador: 1014,
    drible: 90,
    forca: 60,
    foto: "imagem14.png",
    idade: 28,
    nacionalidade: "Brasil",
    nome: "Raphinha",
    peso: 68,
    posicao: "PD",
    velocidade: 88
  },
  {
    agilidade: 82,
    altura: 190,
    clube_atual: "Real Madrid",
    codigo_jogador: 1015,
    drible: 82,
    forca: 84,
    foto: "imagem15.jpg",
    idade: 22,
    nacionalidade: "Inglaterra",
    nome: "Jude Bellingham",
    peso: 75,
    posicao: "MC",
    velocidade: 81
  },
  {
    agilidade: 91,
    altura: 178,
    clube_atual: "PSG",
    codigo_jogador: 1016,
    drible: 92,
    forca: 64,
    foto: "imagem16.png",
    idade: 24,
    nacionalidade: "Geórgia",
    nome: "Khvicha Kvaratskhelia",
    peso: 70,
    posicao: "PE",
    velocidade: 85
  },
  {
    agilidade: 84,
    altura: 186,
    clube_atual: "Barcelona",
    codigo_jogador: 1017,
    drible: 81,
    forca: 80,
    foto: "imagem17.jpg",
    idade: 37,
    nacionalidade: "Polônia",
    nome: "Robert Lewandowski",
    peso: 81,
    posicao: "ATA",
    velocidade: 74
  },
  {
    agilidade: 90,
    altura: 171,
    clube_atual: "Tottenham",
    codigo_jogador: 1018,
    drible: 87,
    forca: 70,
    foto: "imagem18.png",
    idade: 33,
    nacionalidade: "Coreia do Sul",
    nome: "Son Heung-min",
    peso: 67,
    posicao: "PE",
    velocidade: 89
  },
  {
    agilidade: 83,
    altura: 188,
    clube_atual: "Chelsea",
    codigo_jogador: 1019,
    drible: 79,
    forca: 85,
    foto: "imagem19.jpg",
    idade: 27,
    nacionalidade: "Argentina",
    nome: "Enzo Fernandez",
    peso: 78,
    posicao: "MC",
    velocidade: 74
  },
  {
    agilidade: 86,
    altura: 178,
    clube_atual: "Arsenal",
    codigo_jogador: 1020,
    drible: 89,
    forca: 67,
    foto: "imagem20.png",
    idade: 24,
    nacionalidade: "Brasil",
    nome: "Gabriel Martinelli",
    peso: 75,
    posicao: "PE",
    velocidade: 91
  },
  {
    agilidade: 78,
    altura: 195,
    clube_atual: "Atlético de Madrid",
    codigo_jogador: 1021,
    drible: 73,
    forca: 90,
    foto: "imagem21.jpg",
    idade: 26,
    nacionalidade: "Eslovênia",
    nome: "Jan Oblak",
    peso: 87,
    posicao: "GOL",
    velocidade: 52
  },
  {
    agilidade: 88,
    altura: 180,
    clube_atual: "Bayern de Munique",
    codigo_jogador: 1022,
    drible: 86,
    forca: 76,
    foto: "imagem22.png",
    idade: 22,
    nacionalidade: "Alemanha",
    nome: "Jamal Musiala",
    peso: 72,
    posicao: "MEI",
    velocidade: 85
  },
  {
    agilidade: 85,
    altura: 178,
    clube_atual: "Milan",
    codigo_jogador: 1023,
    drible: 84,
    forca: 73,
    foto: "imagem23.jpg",
    idade: 26,
    nacionalidade: "Portugal",
    nome: "Rafael Leao",
    peso: 81,
    posicao: "PE",
    velocidade: 94
  },
  {
    agilidade: 82,
    altura: 185,
    clube_atual: "Manchester United",
    codigo_jogador: 1024,
    drible: 81,
    forca: 78,
    foto: "imagem24.png",
    idade: 30,
    nacionalidade: "Portugal",
    nome: "Bruno Fernandes",
    peso: 76,
    posicao: "MEI",
    velocidade: 74
  },
  {
    agilidade: 80,
    altura: 184,
    clube_atual: "Barcelona",
    codigo_jogador: 1025,
    drible: 79,
    forca: 82,
    foto: "imagem25.jpg",
    idade: 28,
    nacionalidade: "Uruguai",
    nome: "Ronald Araujo",
    peso: 79,
    posicao: "ZAG",
    velocidade: 81
  },
  {
    agilidade: 87,
    altura: 177,
    clube_atual: "Napoli",
    codigo_jogador: 1026,
    drible: 88,
    forca: 66,
    foto: "imagem26.png",
    idade: 24,
    nacionalidade: "Nigéria",
    nome: "Victor Osimhen",
    peso: 78,
    posicao: "ATA",
    velocidade: 92
  },
  {
    agilidade: 89,
    altura: 173,
    clube_atual: "Barcelona",
    codigo_jogador: 1027,
    drible: 91,
    forca: 63,
    foto: "imagem27.jpg",
    idade: 22,
    nacionalidade: "Espanha",
    nome: "Pedri",
    peso: 60,
    posicao: "MC",
    velocidade: 78
  },
  {
    agilidade: 83,
    altura: 181,
    clube_atual: "PSG",
    codigo_jogador: 1028,
    drible: 85,
    forca: 74,
    foto: "imagem28.png",
    idade: 27,
    nacionalidade: "Marrocos",
    nome: "Achraf Hakimi",
    peso: 73,
    posicao: "LD",
    velocidade: 95
  },
  {
    agilidade: 86,
    altura: 182,
    clube_atual: "Manchester City",
    codigo_jogador: 1029,
    drible: 86,
    forca: 77,
    foto: "imagem29.jpg",
    idade: 24,
    nacionalidade: "Inglaterra",
    nome: "Phil Foden",
    peso: 70,
    posicao: "MEI",
    velocidade: 84
  },
  {
    agilidade: 81,
    altura: 189,
    clube_atual: "Inter de Milão",
    codigo_jogador: 1030,
    drible: 80,
    forca: 88,
    foto: "imagem30.png",
    idade: 27,
    nacionalidade: "Argentina",
    nome: "Lautaro Martinez",
    peso: 81,
    posicao: "ATA",
    velocidade: 83
  }
];

export const banners = [
  "./images/banner0.jpg",
  "./images/banner1.jpg",
  "./images/banner2.jpg",
  "./images/banner3.jpg",
  "./images/banner4.jpg",
  "./images/banner5.jpg",
  "./images/banner6.jpg",
  "./images/banner7.jpg",
  "./images/banner8.jpg",
]